curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs
sudo apt install nodejs npm
sudo npm install -g @fleek-platform/cli
fleek
fleek login
#wait here and display the output generated by fleek login cmd and wait until it receives the response
mkdir ~/fleek-quick-start
cd ~/fleek-quick-start
echo "Hello world" > index.html
fleek sites init

#This will Prompt ✔ Please specify the directory containing the site files to be uploaded just enter . (a dot)

#This will prompt ✔ Would you like to include the optional "build" command? just enter no

#This will prompt ✔ Select a format for saving the site's configuration: just select JSON (fleek.config.json) & Enter

#handle this input from user according so that it does not disturb the script flow

fleek sites deploy
